import { Multiplier } from './multipliers.model';

export const DefensiveManeouversList: Multiplier[] = [
{ name: 'Manobra de Combate',
  DamageMultiplier: 1,
  PrecisionMultiplier: 1,
  NDMultiplier: 1,
  ResistenceMultiplier: 1 },

{ name: 'Preparar para impacto',
  DamageMultiplier: 1,
  PrecisionMultiplier: 1,
  NDMultiplier: 0.75,
  ResistenceMultiplier: 1.125 },

{ name: 'Defesa Arriscada',
  DamageMultiplier: 1,
  PrecisionMultiplier: 1,
  NDMultiplier: 1.25,
  ResistenceMultiplier: 0.875 },

{ name: 'Defesa Total',
  DamageMultiplier: 1,
  PrecisionMultiplier: 1,
  NDMultiplier: 1.5,
  ResistenceMultiplier: 1 },
];

export const OffensiveManeouversList: Multiplier[] = [
  { name: 'Manobra de Combate',
    DamageMultiplier: 1,
    PrecisionMultiplier: 1,
    NDMultiplier: 1,
    ResistenceMultiplier: 1 },

  { name: 'Ataque Poderoso',
    DamageMultiplier: 1.25,
    PrecisionMultiplier: 0.75,
    NDMultiplier: 1,
    ResistenceMultiplier: 1 },

  { name: 'Ataque Preciso',
    DamageMultiplier: 0.75,
    PrecisionMultiplier: 1.25,
    NDMultiplier: 1,
    ResistenceMultiplier: 1 },

  { name: 'Mirar',
    DamageMultiplier: 1.5,
    PrecisionMultiplier: 1,
    NDMultiplier: 1,
    ResistenceMultiplier: 1 }
  ];

export const StatusList = [
  { name: 'Status',
    DamageMultiplier: 1,
    PrecisionMultiplier: 1,
    NDMultiplier: 1,
    ResistenceMultiplier: 1,
    StatusDamage: 0 },
  { name: 'Alucinação',
    DamageMultiplier: 1,
    PrecisionMultiplier: 1,
    NDMultiplier: 1,
    ResistenceMultiplier: 1,
    StatusDamage: 0 },
  { name: 'Atordoamento',
    DamageMultiplier: 1,
    PrecisionMultiplier: 0.875,
    NDMultiplier: 0.875,
    ResistenceMultiplier: 1,
    StatusDamage: 0 },
  { name: 'Bersek',
    DamageMultiplier: 1.25,
    PrecisionMultiplier: 1,
    NDMultiplier: 0.75,
    ResistenceMultiplier: 1,
    StatusDamage: 0 },
  { name: 'Cegueira',
    DamageMultiplier: 1,
    PrecisionMultiplier: 0.75,
    NDMultiplier: 1,
    ResistenceMultiplier: 1,
    StatusDamage: 0 },
  { name: 'Congelamento',
    DamageMultiplier: 1,
    PrecisionMultiplier: 1,
    NDMultiplier: 0.75,
    ResistenceMultiplier: 1,
    StatusDamage: 0.05 },
  { name: 'Embriaguês',
    DamageMultiplier: 1,
    PrecisionMultiplier: 0.875,
    NDMultiplier: 0.875,
    ResistenceMultiplier: 1,
    StatusDamage: 0 },
  { name: 'Fascínio',
    DamageMultiplier: 0.75,
    PrecisionMultiplier: 1,
    NDMultiplier: 1,
    ResistenceMultiplier: 1,
    StatusDamage: 0 },
  { name: 'Hemorragia',
    DamageMultiplier: 1,
    PrecisionMultiplier: 1,
    NDMultiplier: 1,
    ResistenceMultiplier: 1,
    StatusDamage: 0.05 },
  { name: 'Fascinio',
    DamageMultiplier: 0.75,
    PrecisionMultiplier: 1,
    NDMultiplier: 1,
    ResistenceMultiplier: 1,
    StatusDamage: 0 },
  { name: 'Medo',
    DamageMultiplier: 1,
    PrecisionMultiplier: 0.75,
    NDMultiplier: 1.125,
    ResistenceMultiplier: 1,
    StatusDamage: 0 },
  { name: 'Paralisia',
    DamageMultiplier: 1,
    PrecisionMultiplier: 1,
    NDMultiplier: 0.75,
    ResistenceMultiplier: 1,
    StatusDamage: 0 },
  { name: 'Pesado',
    DamageMultiplier: 1,
    PrecisionMultiplier: 1,
    NDMultiplier: 0.75,
    ResistenceMultiplier: 1,
    StatusDamage: 0 },
  { name: 'Queimadura',
    DamageMultiplier: 1,
    PrecisionMultiplier: 1,
    NDMultiplier: 1,
    ResistenceMultiplier: 0.75,
    StatusDamage: 0.05 },
  { name: 'Sonolência',
    DamageMultiplier: 1,
    PrecisionMultiplier: 0.875,
    NDMultiplier: 0.875,
    ResistenceMultiplier: 1,
    StatusDamage: 0 },
  { name: 'Sufocamento',
    DamageMultiplier: 1,
    PrecisionMultiplier: 1,
    NDMultiplier: 1,
    ResistenceMultiplier: 1,
    StatusDamage: 0.05 },
  { name: 'Veneno',
    DamageMultiplier: 1,
    PrecisionMultiplier: 1,
    NDMultiplier: 1,
    ResistenceMultiplier: 1,
    StatusDamage: 0.05 },

];
